name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - name: Build Go Sidecar
        shell: bash
        run: |
          TARGET_TRIPLE=$(rustc -Vv | grep host | cut -d ' ' -f 2)
          mkdir -p src-tauri/bin
          go build -ldflags="-s -w" -o "src-tauri/bin/sidecar-$TARGET_TRIPLE" ./src-tauri/background/main.go
          if [ "${{ matrix.platform }}" == "windows-latest" ]; then
            mv "src-tauri/bin/sidecar-$TARGET_TRIPLE" "src-tauri/bin/sidecar-$TARGET_TRIPLE.exe"
          fi

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # tauri-action replaces this with the actual tag
          releaseName: 'Veilid Reddit MySpace v__VERSION__'
          releaseBody: 'See CHANGELOG.md for details.'
          releaseDraft: true
          prerelease: false
